# Generated by Django 4.0.5 on 2022-06-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='new_name', max_length=30, verbose_name='Name')),
                ('anons', models.CharField(default='new_anons', max_length=250, verbose_name='Anons')),
                ('full_text', models.TextField(verbose_name='Post')),
                ('date', models.DateTimeField(verbose_name='Date of publish')),
            ],
        ),
    ]
